### ISSUE TITLE
Cross-Classification and Tabulation issue (for summarizing change by enumeration area)

### ISSUE THREAD

**Issue by MartinWF** [GIS4DEV/Q-and-A#10]
Hi all,

I had an issue with the Grid - Analysis --> Cross-Classification and Tabulation module for summarizing change by enumeration area - and I think it's an issue that others might encounter, too. 

So, when SAGA calculates the change classes, the first class is assigned a '0,' the second class is assigned a '1,' the third a '2', and so forth. Herein lies the problem, however, since the Cross-Classification and Tabulation module won't include the first change class (the one that was assigned a '0').  Therefore, to solve this, we've got to use the Grid Calculator module (Grid - Calculus --> Grid Calculator) to add 1 to all of the classes. This will allow the Cross-Classification and Tabulation module to include all of the classes. To do this, simply load the change grid into the Grid Calculator module, write 'g1+1' in the 'Formula' box (this will automatically add 1 to all the change class values) and execute. Then use the resulting grid in the Cross-Classification and Tabulation module and you should have all the change classes.

So, the steps:
1) Grid - Calculus --> Grid Calculator (g1+1 in the formula box)
2) In the Cross-Classification and Tabulation module, use the grid created by step [1] together with your enumeration areas to get a cross-tabulation table that includes all of the change classes.

I hope that helps.

Martin.

**Comment by jeanniebartlett** [comment]
Thank you, Martin! That's awesome!
I encountered the same problem, but ultimately decided that since the lost
category was Water>>Water, I could just eliminate it from my analysis. So
that's another option for people in a similar situation to me who don't
want to do the extra step!
Jeannie

**Comment by josephholler** [comment]
Thanks, Martin!
