### ISSUE TITLE
Spatial Accuracy Errors that I don't think can be solved with transformations

### ISSUE THREAD

**Issue by jeanniebartlett** [GIS4DEV/Q-and-A#5]
I'm having trouble determining what, if anything, I can do to make my shapefiles match OSM. My basic impression is that the administrative boundaries shapefiles were manually digitized from a hardcopy map, and the paper kept shifting and the operator couldn't see the lines they were supposed to be tracing all the time. Regardless of whether that's actually what happened, it at least describes the types of errors in my spatial data.
In many areas, it looks like my layers are just offset by 3-5 km E/W. In other areas, they are offset 5 km N/S. In other areas, they line up. In other areas, the shapes of the lines simply could never match. Maybe there is a more consistent pattern I'm not seeing (possibly an E/W offset?) that could be improved with a transformation? Or, if there's nothing I can do, is it acceptable to go ahead, knowing that I'm propagating errors (boundary errors-->area errors-->density & representation errors)? Or do I need to ditch this country?
![image](https://cloud.githubusercontent.com/assets/11279866/6508136/d1057f40-c324-11e4-9b99-a826727fc8a5.png)
![image](https://cloud.githubusercontent.com/assets/11279866/6508228/93cd0d36-c325-11e4-931a-193adad2349c.png)

**Comment by jeanniebartlett** [comment]
Sorry I forgot to say, in the screenshots, the red dotted lines are from my shapefiles, and the purple ones are from OSM.

**Comment by jeanniebartlett** [comment]
I found a different shapefile for Nigeria administrative boundaries, and mapped it as well. First of all, it does not have all of the current subdivisions (only 549 out of 774), so it can't be my primary shapefile. But also, it does not match either OSM or my original shapefile... my map is beginning to look like spaghetti! The new layer is in blue, below, and the original shapefile is in orange. Sorry I can't make OSM show up brighter.

![image](https://cloud.githubusercontent.com/assets/11279866/6509017/62a6cc6a-c32a-11e4-878b-7a1de7184580.png)

**Comment by josephholler** [comment]
This is a good example of a case where the shapefiles are lacking precision and are too generalized.  If it was an accuracy problem, you could try to do something about it.  But since it's a precision problem, just write about it in your metadata.  Fixing this type of error requires acquiring new data or supplementing what you have with ancillary data.  Sometimes you can find more precise ancillary data to improve the boundaries, such as a good coastline or water bodies layer that can be used to clip the boundaries.

**Comment by jeanniebartlett** [comment]
Thanks Joe!
