### ISSUE TITLE
Spatial Join issue

### ISSUE THREAD

**Issue by MartinWF** [GIS4DEV/Q-and-A#8]
Hi,

I'm having trouble doing a spatial join. I do the following SQL query, but receive only 'NULL' values from the Districts02g file.

SELECT *
FROM Regions LEFT OUTER JOIN Districts02g ON
contains(Regions.geom, Districts02g.Center)

I've used ASTEXT() to confirm that the 'Center' column in Districts02g has values, added these to the map to check that they're correct. Any thoughts?

**Comment by josephholler** [comment]
For any of the spatial operators to work properly, the inputs should all use the same coordinate system.  In our workflows to transform geometries from 4326 (wgs 1984), we created new geometry columns for our custom projection.  Try using that one, rather then Regions.geom.

**Comment by MartinWF** [comment]
Aha. This makes sense. I thought it was already in 110000. Thank you!
