### ISSUE TITLE
Results of 'Close gaps with spline' is solid color

### ISSUE THREAD

**Issue by jeanniebartlett** [GIS4DEV/Q-and-A#9]
The results of my "Close gaps with spline" display as a solid color. When I run my mouse over the map, the z value does change (mostly in the '40s-'80s). When I leave the color type on "Graduated color," the value range is -9123916485102530600 to 9122096992424298500, which makes sense and proves that a reclassification is needed. But when I change the color type to Lookup Table, or use the Lookup Table in Reclassify Grid Values, the lookup table only shows two classes, first 0-10, second 10-20. How do I get the lookup table to show the real values so I can reclassify them?

**Comment by josephholler** [comment]
Personally, I did not bother making a lookup table for this issue.  I went directly to the Reclassify Grid Values module, set the method to simple table, and edited the values in the table manually.
